version: '3.3'
services:

  db:
    ports: 
      - '5431:5431'
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    command: -p 5431

  backend:
    ports: 
      - '8000:8000'
    build: 
      context: ../backend/foodgram
      dockerfile: Dockerfile
    restart: always
    command: "gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: evstigneefff/frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  postgres_data:
